# Pandas užduotys 2

In [29]:
import numpy as np
import pandas as pd

#  1 Sulipdykite iš 4 fragmentų vieną lentelę:

fragmentus rasite [čia](https://github.com/StasysC/Python-2lvl)

* top_left = pd.read_csv('top1-25-1.csv')
* top_right = pd.read_csv('top1-25-2.csv')
* bottom_left = pd.read_csv('top26-50-1.csv')
* bottom_right = pd.read_csv('top26-50-2.csv')

pirmiausiai sujunkite apatinę dalį, tada viršutinę *(yra persidengiančių stulpelių!)*, galiausiai viršų su apačia. Naudokite **.concat()** ir **.merge()** metodus.

,Track.Name,Artist.Name,Genre,Popularity,Beats.Per.Minute,Energy,Danceability,Loudness..dB..,Liveness,Valence.,Length.,Acousticness..,Speechiness.
0,Senorita,Shawn Mendes,canadian pop,79.0,117,55,76,-6,8,75,191,4,3
1,China,Anuel AA,reggaeton flow,92.0,105,81,79,-4,8,61,302,8,9
2,boyfriend (with Social House),Ariana Grande,dance pop,85.0,190,80,40,-4,16,70,186,12,46
3,Beautiful People (feat. Khalid),Ed Sheeran,pop,NaN,93,65,64,-8,8,55,198,12,19
4,Goodbyes (Feat. Young Thug),Post Malone,dfw rap,94.0,150,65,58,-4,11,18,175,45,7

# 2 Sutvarkykite indeksą - padarykite, kad prasidėtų nuo 1.

,Track.Name,Artist.Name,Genre,Popularity,Beats.Per.Minute,Energy,Danceability,Loudness..dB..,Liveness,Valence.,Length.,Acousticness..,Speechiness.
#,,,,,,,,,,,,,
1,Senorita,Shawn Mendes,canadian pop,79.0,117,55,76,-6,8,75,191,4,3
2,China,Anuel AA,reggaeton flow,92.0,105,81,79,-4,8,61,302,8,9
3,boyfriend (with Social House),Ariana Grande,dance pop,85.0,190,80,40,-4,16,70,186,12,46
4,Beautiful People (feat. Khalid),Ed Sheeran,pop,NaN,93,65,64,-8,8,55,198,12,19
5,Goodbyes (Feat. Young Thug),Post Malone,dfw rap,94.0,150,65,58,-4,11,18,175,45,7

# 3 Sukurkite grupavimo pagal žanrą objektą

# 4 kokie žanrai lentelėje pasitaiko daugiau negu 3 kartus?

,Track.Name,Artist.Name,Popularity,Beats.Per.Minute,Energy,Danceability,Loudness..dB..,Liveness,Valence.,Length.,Acousticness..,Speechiness.
Genre,,,,,,,,,,,,
atl hip hop,1,1,1,1,1,1,1,1,1,1,1,1
australian pop,1,1,1,1,1,1,1,1,1,1,1,1
big room,1,1,1,1,1,1,1,1,1,1,1,1
boy band,1,1,1,1,1,1,1,1,1,1,1,1
brostep,2,2,1,2,2,2,2,2,2,2,2,2

In [87]:
newdf[newdf['Energy']>3]['Energy']

Genre
dance pop    8
latin        5
pop          6
Name: Energy, dtype: int64

# 5 Koks žanras pats populiariausias? Koks mažiausiai populiarus?
(pagal populiarumo vidurkį)

electropop 95.0
canadian pop 74.5

# 6 Sukurkite lentelę, kurioje matytųsi, koks žanras turi aukščiausią vidurkį kiekviename indikatoriuje, bei pats vidurkis.
kad nereikėtų daug vargti su stulpelių pavadinimais, galima juos ištraukti su **.columns.tolist()**

       Indikatorius          Žanras  Balai
0        Popularity      electropop     95
1  Beats.Per.Minute      trap music    180
2            Energy  reggaeton flow     80
3      Danceability  r&b en espanol     88
4    Loudness..dB..         brostep   -2.5
5          Liveness         brostep   37.5
6          Valence.        boy band     95
7           Length.  reggaeton flow  305.5
8    Acousticness..  australian pop     69
9      Speechiness.      electropop     34

# 7 Grįžkime prie sulipdytos lentelės. Ištraukite visas eilutes, kurios turi NaN reikšmių.
*filtravimo sąlygose naudokite **.isnull()** funkciją.*

<class 'pandas.core.frame.DataFrame'>
Int64Index: 50 entries, 1 to 50
Data columns (total 13 columns):
Track.Name          50 non-null object
Artist.Name         50 non-null object
Genre               48 non-null object
Popularity          47 non-null float64
Beats.Per.Minute    50 non-null int64
Energy              50 non-null int64
Danceability        50 non-null int64
Loudness..dB..      50 non-null int64
Liveness            50 non-null int64
Valence.            50 non-null int64
Length.             50 non-null int64
Acousticness..      50 non-null int64
Speechiness.        50 non-null int64
dtypes: float64(1), int64(9), object(3)
memory usage: 5.5+ KB

,Track.Name,Artist.Name,Genre,Popularity,Beats.Per.Minute,Energy,Danceability,Loudness..dB..,Liveness,Valence.,Length.,Acousticness..,Speechiness.
#,,,,,,,,,,,,,
4,Beautiful People (feat. Khalid),Ed Sheeran,pop,NaN,93,65,64,-8,8,55,198,12,19
19,Lalala,Y2K,NaN,88.0,130,39,84,-8,14,50,161,18,8
25,bad guy (with Justin Bieber),Billie Eilish,electropop,NaN,135,45,67,-11,12,68,195,25,30
48,Happier,Marshmello,brostep,NaN,100,79,69,-3,17,67,214,19,5
50,Cross Me (feat. Chance the Rapper & PnB Rock),Ed Sheeran,NaN,82.0,95,79,75,-6,7,61,206,21,12

# 8 Stulpelyje 'Genre' NaN reikšmes pakeiskite į 'pop'

# 9 Stulpelyje 'Popularity' trūkstamas reikšmes pakeiskite į stulpelio vidurkį